version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  pre_build:
    commands:
      ${env_vars_snippet}
      - ASSUME_ROLE=$cicd_role
      ${assume_role_snippet}

  build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $SRC --paths "$DST:-/*"
