version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - npm install

  # pre_build:
  #   commands:
  #     - npm run test
      
  build:
    commands:
      - npm run build
      - aws s3 sync ./public/ s3://nsph-static-website-maximum-gorilla --delete
      - aws cloudfront create-invalidation --distribution-id EYWU0YJFO1TAD

artifacts:
  files:
    - 'output/**/*'
