version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - npm install

  # pre_build:
  #   commands:
  #     - npm run test
      
  build:
    commands:
      - npm run build
      
  post_build:
    commands:
      - aws_credentials=$(aws sts assume-role --role-arn arn:aws:iam::382888529141:role/utility_assume_role --role-session-name cicd)
      - export AWS_ACCESS_KEY_ID=$(echo $aws_credentials | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $aws_credentials | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $aws_credentials | jq -r '.Credentials.SessionToken')

      - aws s3 sync ./public/ s3://nsph-static-website-maximum-gorilla/
      - aws cloudfront create-invalidation --distribution-id EYWU0YJFO1TAD

artifacts:
  files:
    - 'output/**/*'
