version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  install:
    commands:
      - echo Starting the Docker daemon...
      - /usr/local/bin/dockerd-entrypoint.sh
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - echo build
