version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  install:
    commands:
      - cd $SRC
      - tfswitch

  pre_build:
    commands:
      - terrascan init
      - terrascan scan

  build:
    commands:
      - terraform apply -var-file=${ENV}.tfvars -auto-approve
