version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  install:
    commands:
      - cd $SRC
      - tfswitch || echo .

  pre_build:
    commands:
      - terraform init
      # - terrascan scan

  build:
    commands:
      - terraform apply -auto-approve $(eval "echo $ARGS")
