version: 0.2

env:
  shell: bash
  exported-variables:
    - OUTPUT

phases:
  install:
    commands:
      - cd $SRC
      - tfswitch || echo .
      ${env_vars_snippet}

  pre_build:
    commands:
      - export TF_INPUT=0
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve $(eval "echo $ARGS")
